### ISSUE TITLE
Do not count bots

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/top-10#134]
As the title suggest, the plugin should detect any bots and not increment the search counter if the page load is via a bot.

**Comment by Zodiac1978** [comment]
For [Statify](https://github.com/pluginkollektiv/statify) we are using [CrawlerDetect](https://github.com/JayBizzle/Crawler-Detect), which looks a little bit more "complete".

**Comment by ajaydsouza** [comment]
That looks brilliant. Both your plugin and CrawlerDetect. I’m going to mark this as a feature to add to enhance the bot detection.
I have plans on capturing the referral as well but need to figure out a clean way to do it without exploding the database.
