### ISSUE TITLE
Number of posts is not saved in gutenberg editor block

### ISSUE THREAD

**Issue by dvuljanic984** [WebberZone/top-10#154]
**Describe the bug**
When Top 10 Popular Posts block inserted in gutenberg and number of posts changed to any  number and saved everytime editor is reloaded it is reverted to default 6 posts

**To Reproduce**
1. Open new page/post
2. Insert  Top 10 Popular Posts block
3. Change number of posts for inserted block to any number except 6
4. Click Update 
5. Refresh 
6. it is reverted to 6

**To Reproduce**
1. Open new page/post
2. Change Gutenberg editor to Code view
3. paste 
4. click somwhere outside edit area
5. {"limit":"2"} is removed

**Desktop:**
 - OS: Windows 10
 - Browser Chrome
 - Version Version 116.0.5845.

**Additional context**
Tested also in Firefox

**Comment by ajaydsouza** [comment]
Thanks. I was able to replicate this. Looks like something went wrong with the block with the last update.

**Comment by dvuljanic984** [comment]
> Thanks. I was able to replicate this. Looks like something went wrong with the block with the last update to WordPress or Gutenberg or the plugin. I'll investigate.
> 
> Update: I noticed if you use `{"limit":2}` without the quotes it works.

No Problem, thx for quick response. I tested it also, that way it works. Thx.
When do you think you will push the update with the fix ?

**Comment by ajaydsouza** [comment]
Not sure yet. I need to dig a bit into fixing this because the above one is a temporary workaround. The good news is that my Contextual Related Posts plugin works as desired so I need to replicate that fix.
