### ISSUE TITLE
It is not possible to create shortcodes with different categories

### ISSUE THREAD

**Issue by ildomandatore** [WebberZone/top-10#159]
I wanted to add about fifteen shortcodes to the homepage https://giocone.com/, each with a different category. Unfortunately I have the sum of all the categories.

https://imgur.com/a/JWTkGJI

https://imgur.com/a/RTdtJGP

**Comment by ajaydsouza** [comment]
Does it work if you use a = instead of : in the shortcode?

**Comment by ildomandatore** [comment]
I don't understand why the layout of the images of the games for girls on the homepage are distorted.

https://imgur.com/a/FvY0i4a

**Comment by ajaydsouza** [comment]
Please can you create a new post in the support forum with the link to your site and other details as needed. I use GitHub to track issues for features or bugs (once confirmed).

https://wordpress.org/support/plugin/top-10/

**Comment by ildomandatore** [comment]
I've solved it, but I'm been banned from Forum. I hope you'll use github for support in future. Wordpress forum has bad rules to follow.

**Comment by ajaydsouza** [comment]
I'm sorry to hear that. I'm not quite keen to use Github for issues, but if it's a genuine use of the plugin, I can consider it. Definitely not for basic usage or CSS. Please check the knowledge base for issues and I'm happy to add more articles to the knowledge base as it also helps other users.

**Comment by ildomandatore** [comment]
I have the same errors again: the two shortcodes show the same results.

These are the shortcodes in the 2 players category:
[tptn_list thumb_width=300 thumb_height=158 include_cat_ids=839 daily_range=30] [tptn_list thumb_width=300 thumb_height=158 include_cat_ids=839 daily_range=14]

In fact I was wondering why on the homepage I didn't need to visit the pages to maintain a good number of popular posts, since there are very few users on the site at the moment.

[tptn_list thumb_width=300 thumb_height=158 include_cat_ids=839 daily_range=7]

**Comment by ajaydsouza** [comment]
Shortcode is missing `daily=1`. Can you try that?

**Comment by ildomandatore** [comment]
thank you.

**Comment by ildomandatore** [comment]
I have 2 other problems: I have to clear the cache if I make changes with your plugin and not with others and 1 shortcode out of many doesn't work.

I did the comparison and found no errors.
[tptn_list include_cat_ids=732 daily_range=30 daily=1] [tptn_list include_cat_ids=732 daily_range=14 daily=1]

The second shortcode shows a blank space with nothing.

**Comment by ildomandatore** [comment]
Where should I look on Query Monitor? I can't find the path WP_Query->get_posts().

https://imgur.com/a/qmOHrFx If you not see image: https://postimg.cc/5XQyVJTr/dc76234c

**Comment by ajaydsouza** [comment]
Please see here: https://webberzone.com/support/knowledgebase/debugging-with-query-monitor/

**Comment by ildomandatore** [comment]
https://imgur.com/a/AGfcct3 or if you not see image: https://postimg.cc/HVTc4hSN/5a676b7b

Thanks for the guide, because I would never have found the path WP_Query->get_posts.

**Comment by ajaydsouza** [comment]
The queries look fine to me. The older date shows 7 posts and the newer shows 1.

You can run these on phpmyadmin to verify which are these posts.

**Comment by ildomandatore** [comment]
What can I do to solve the problem? I repaired and optimized the tables. I still have the cache problem. If I remember correctly, there is your own cache option.

Strangely enough, I see a post about it too. But the 3 strategy games I saw today do not appear.

**Comment by ajaydsouza** [comment]
Have you disabled the cache in the plugin settings page?

**Comment by ildomandatore** [comment]
Some your settings could give conflits with Cache plugins?

**Comment by ajaydsouza** [comment]
It's not a conflict. It's a separate caching system designed to work with or independently or caching systems. If you're in building mode, I suggest keeping it off. Once you are in production, then turn it on for performance.

Obviously if you have your own caching that you're happy with then you don't need that of the plugin.
