### ISSUE TITLE
Bad performance

### ISSUE THREAD

**Issue by ildomandatore** [WebberZone/top-10#166]
I've tried Firefox with and without your plugin and find that your plugin creates slowness.

https://imgur.com/a/S9S8FKx

Top 10 Version 3.3.4

https://imgur.com/a/uieSnC6

**Comment by ajaydsouza** [comment]
I missed this. That does look bad. Can you try regenerating the Primary Key under the Tools page - and if that doesn't work "Recreate Database Tables".
