### ISSUE TITLE
Not tracking

### ISSUE THREAD

**Issue by coldpumpkin** [WebberZone/top-10#17]
Is there any way to track visits even if the_content is not there?

**Comment by ajaydsouza** [comment]
You could add: `<?php echo tptn_add_viewed_count( ' ' ); ?>` somewhere in your theme to display the tracker code.

**Comment by coldpumpkin** [comment]
Alright, that seems to work just fine =) thanks.

**Comment by ajaydsouza** [comment]
Thanks for confirming :)
