### ISSUE TITLE
Top 10 not working on the bedrock structure

### ISSUE THREAD

**Issue by mostafasoufi** [WebberZone/top-10#32]
Hi @ajaydsouza,

I've been using [bedrock structure](https://github.com/roots/bedrock) and it's seems top 10 not work on the bedrock.

in bellow files:
```
top-10-addcount.js.php
top-10-counter.js.php
```

Should be change:
`$wp_config_filename = '/wp-load.php';`

to:
`$wp_config_filename = '/wp/wp-load.php';`

Regards

**Comment by ajaydsouza** [comment]
That is unfortunately an issue with the external js files. In this case, the option would be to turn off the "external file" tracking in the settings page. The plugin stops using the above files then.

I'm working on a new ajax based tracker using a js file which is a bit more universal

**Comment by mostafasoufi** [comment]
Oky, thanks for that :+1:
