### ISSUE TITLE
Options get reset after porting db

### ISSUE THREAD

**Issue by webakimbo** [WebberZone/top-10#38]
I'm hosting a site on WP Engine. Periodically I export my local db, changing all url references via search/replace, and import to the WP Engine production db.

Every time I do this, all Top 10 settings are restored to the defaults. It's a pain to have to reset these each time. Can you reproduce this on your end?

**Comment by ajaydsouza** [comment]
What's the URL changes that you're doing. The issue with changing URL in the sql file between imports is that the array holding options is no longer proper serialised. And, so the import fails. 

What URL are you changing between? Ideally the length should be same. Or alternatively use a plugin to export and import. 

For my tests I use example.lcl for local vs example.com for live

**Comment by webakimbo** [comment]
smllp.local -> smllp.wpengine.com

So I can see why the serialization would be off, though I don't understand why this wouldn't happen with other plugins? Also didn't know that would cause the options to fail to carry over.

The only Top 10 option that contains a URL appears to be thumb_default, which I don't use. Maybe a short-term fix is to delete this entry entirely?

**Comment by ajaydsouza** [comment]
It's because of the thumb url. One option when you are exporting would be to empty this entry, save options and then export.

But, you should see a similar issue with customizer options. I had a similar problem when I used different length urls and kept losing all my settings
