### ISSUE TITLE
Count a visit by JS and PHP?

### ISSUE THREAD

**Issue by coldpumpkin** [WebberZone/top-10#53]
I'm sorry if this has been already answered but how do I make a count either by using JS and PHP?

For example, I'm using fancybox and I can insert whatever code I want inside the callback when opening a post link. I want to add a piece of code there (JS/Jquery) to count a visit (the user is not technically entering the post page but he's viewing some content through fancybox). How can I achieve this?

Also, regarding PHP, there used to be this code:

`<?php echo tptn_add_viewed_count( ' ' ); ?> `

But it's not working anymore. Any way to achieve the same result through PHP?

**Comment by ajaydsouza** [comment]
The code above should update the count whenever the post is viewed. It just spits out the JS code needed for this. What do you see when you browse your site when adding the code?

**Comment by coldpumpkin** [comment]
I don't know exactly what I did (maybe I updated the plugin) since I wrote this issue but I'm not even using the PHP code anymore. Whenever I visit the post page it updates the visit count.

However I still need to count a visit with a JS solution :X

**Comment by coldpumpkin** [comment]
Is this it?:
```
jQuery.ajax({
	url: "http://localhost/mysite/",
	data: {
		top_ten_id: <post id>,
		top_ten_blog_id: 1,
		activate_counter: 11,
		top10_rnd: (new Date()).getTime() + "-" + Math.floor(Math.random() * 100000)
	}
});

What do top_ten_blog_id and active_counter refer to though?
```

**Comment by ajaydsouza** [comment]
Yes. That's the one.

The blog id applies in case of multi site as the plugin uses the same table but records hits with a separate blog id. 

activate_counter is to indicate if daily and/or overall counter should be tracked

**Comment by coldpumpkin** [comment]
Thanks for the clarification! Cheers

**Comment by coldpumpkin** [comment]
Is there a way to replicate this using JS?:

```
		$include_code = true;
		if ( ( $post_author ) && ( ! $tptn_settings['track_authors'] ) ) {
			$include_code = false;
		}
		if ( ( $current_user_admin ) && ( ! $tptn_settings['track_admins'] ) ) {
			$include_code = false;
		}
		if ( ( $current_user_editor ) && ( ! $tptn_settings['track_editors'] ) ) {
			$include_code = false;
		}
```

**Comment by ajaydsouza** [comment]
Not in JS as I know. Any reason you're not replicating this via PHP?

**Comment by coldpumpkin** [comment]
Because I need to add a count through jQuery for those who view the post (in this case the post is an image) in Fancybox.

**Comment by ajaydsouza** [comment]
How are you applying that code to the post in Fancybox? I am not too well versed in jQuery, but, I'm not sure if you can get the user status from WordPress using jQuery.

**Comment by coldpumpkin** [comment]
Like this:

```
beforeShow: function(instance, slide) {
    jQuery.ajax({
        url: siteURL,
        data: {
            top_ten_id: $(slide.opts.$orig).attr('post-id'),
            top_ten_blog_id: 1,
            activate_counter: 11,
            top10_rnd: (new Date()).getTime() + "-" + Math.floor(Math.random() * 100000)
        }
    }); 
},
```

It adds a count when showing the slide (post). Anyway I want to prevent counts to be added for admins, so my work-around is having this code at header.php

`<?php if (current_user_can('administrator')) { ?><isadmin><?php } ?>`

And then I simply added `if (!$('isadmin').length) {` before the count code :D
