### ISSUE TITLE
The number of total visited didn't update anymore

### ISSUE THREAD

**Issue by bluegray1015** [WebberZone/top-10#61]
Firstly, thanks for your WP plugin, it's really useful and helpful for tracking the number of visited on my blog. However, I have been encountering an issue for a while.

The number of total visited time hasn't been updated since 2 months ago, although the number of daily visited was updated when I refresh the browser. As a result, I checked the database. I found there are many duplicate records in the wp_top_ten table such as 
```
mysql> select * from wp_top_ten where postnumber = 8422;
+------------+-----------+---------+
| postnumber | cntaccess | blog_id |
+------------+-----------+---------+
|       8422 |     17534 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
|       8422 |         1 |       1 |
+------------+-----------+---------+
11 rows in set (0.00 sec)
```

I am not familiar with your project, so I am wondering is it correct?

And the records from wp_ten_top_daily is as below:
```
mysql> select * from wp_top_ten_daily where postnumber = 8422;
+------------+-----------+---------------------+---------+
| postnumber | cntaccess | dp_date             | blog_id |
+------------+-----------+---------------------+---------+
|       8422 |         1 | 2018-01-24 12:00:00 |       1 |
|       8422 |         1 | 2018-02-04 15:00:00 |       1 |
|       8422 |         2 | 2018-02-04 18:00:00 |       1 |
|       8422 |         2 | 2018-02-04 21:00:00 |       1 |
|       8422 |         2 | 2018-02-04 22:00:00 |       1 |
|       8422 |         1 | 2018-02-05 00:00:00 |       1 |
|       8422 |         2 | 2018-02-05 01:00:00 |       1 |
+------------+-----------+---------------------+---------+
7 rows in set (0.00 sec)
```

I am not sure why the first record was created on `2018-01-24 12:00:00`. Is because the scheduled maintenance will delete entries older than 90 days in the daily tables?

**Comment by ajaydsouza** [comment]
The second table makes sense to me. You've got the various line items because of the hourly capture. If you have maintenance disabled it will delete entries older than 90 days.

The first table looks like an error with the duplicates in there. You can use the Clean duplicates button in tools to merge these together.

Can you please check that you have the PRIMARY KEY in the table? I'm working on another button in the tools area to fix the primary key that has been broken in a few installs.

**Comment by bluegray1015** [comment]
Hi, there is no PRIMARY KEY  in wp_top_ten table. I was surprised that there is no PK here.

**Comment by ajaydsouza** [comment]
That might be the issue. Can you please run:

`ALTER TABLE wp_top_ten ADD PRIMARY KEY(postnumber, blog_id)
`

**Comment by bluegray1015** [comment]
It's all set, hope it will work. Thanks for your prompt response.

```
mysql> DESCRIBE wp_top_ten;
+------------+------------+------+-----+---------+-------+
| Field      | Type       | Null | Key | Default | Extra |
+------------+------------+------+-----+---------+-------+
| postnumber | bigint(20) | NO   | PRI | 0       |       |
| cntaccess  | bigint(20) | YES  |     | NULL    |       |
| blog_id    | bigint(20) | NO   | PRI | 1       |       |
+------------+------------+------+-----+---------+-------+
3 rows in set (0.00 sec)
```

**Comment by ajaydsouza** [comment]
Thanks. Please let me know if the issue continues. The recent update caused an issue with the PRIMARY KEYS not being recreated which is a bit frustrating. I'm creating a button as I mentioned above in the Tools page which should hopefully let everyone fix it without the database access

**Comment by bluegray1015** [comment]
After added the PK for the wp_top_ten top, everything is working properly. So I close the issue. Thanks @ajaydsouza

**Comment by dennisaskeland** [comment]
I've encountered the same problem with missing primary key. After updating the plugin the total counter stays at 1, but the daily counter updates as expected. I've tried your solution above but when trying to alter the wp_top_ten table and setting primary key I get this error;

"Duplicate entry '77037-1' for key 'PRIMARY'"

Any suggestions to how I can fix this without losing all my data?

**Comment by dennisaskeland** [comment]
Using DESCRIBE wp_top_ten I get the results on the image attached 
<img width="353" alt="screenshot 2019-01-10 at 12 09 20" src="https://user-images.githubusercontent.com/9537270/50964858-a675c580-14d0-11e9-9fdb-ab27999c4e97.png">

I can try your described solution

**Comment by dennisaskeland** [comment]
Hello @ajaydsouza,

I still have the same problem with total views not updating. I am unable to recreate primary key from both SQL and Top 10 tools. When I try your described solution from above the new tables has the primary key, but when importing the old data as .sql the tables are overwrite and missing PK again.

If I export the data as .csv, recreate the tables and import the .csv entries I get the same error "Duplicate entry '77037-1' for key 'PRIMARY'".

I've tried the merge duplicates button in tools, but it appears to have no effect

**Comment by ajaydsouza** [comment]
When you're importing the old data, are you dropping the tables? You'll need to just import the values of the entries and not the table structure again.

When importing, can you check a) that the table is fully empty; and b) that you don't have a duplicate in your data? It might be possible you have a few duplicates which is why importing with the keys activated is causing that issue.

Have you tried the merge duplicates before exporting the data?

**Comment by dennisaskeland** [comment]
I've tried to merge duplicates from within the Top 10 tools and then export the data. But it doesn't seem to work as I still have duplicates when importing after dropping tables and recreating them by activating the plugin and starting off with empty tables but with PK
