### ISSUE TITLE
REST API

### ISSUE THREAD

**Issue by ajaydsouza** [WebberZone/top-10#67]
Add Rest API endpoint to receive the top posts

**Comment by gam271** [comment]
Love to help if you still need it! @ajaydsouza

**Comment by ajaydsouza** [comment]
@gam271 Yes please - I'm still not familiar with the REST API so any contributions more than welcome!

**Comment by gam271** [comment]
@ajaydsouza Starting now!

**Comment by gam271** [comment]
@ajaydsouza Where is the current API documentation?

**Comment by ajaydsouza** [comment]
Still to be written!

But, please see an example: https://gist.github.com/ajaydsouza/c8defd4b46e53240e376
This use [get_tptn_pop_posts()](https://github.com/WebberZone/top-10/blob/v2.7.0/includes/public/display-posts.php#L277) to fetch the posts only.

This should be similar to implementing it for the Shortcode - https://github.com/WebberZone/top-10/blob/v2.7.0/includes/modules/shortcode.php#L16
This fetches and displays the posts using [tptn_pop_posts()](https://github.com/WebberZone/top-10/blob/v2.7.0/includes/public/display-posts.php#L21)

It allows all the settings to be passed as an array - the main ones are here https://webberzone.com/support/knowledgebase/top-10-shortcodes/

**Comment by Sukkoto** [comment]
@ajaydsouza, do you need REST API docs written? I'd like to help if you do. 

I'm completely new to REST API docs and Github, so my help would be extremely slow, and I might need a bit of hand holding, but I'd do my best.

**Comment by ajaydsouza** [comment]
@Sukkoto 

Actually, this issue is primarily to add REST API endpoints to the plugin so that the tracker can be updated using the REST API and also allow popular posts to be pulled using the API.

**Comment by elmissouri16** [comment]
@ajaydsouza  thanks for the amazing work, any progress on this?

**Comment by ajaydsouza** [comment]
@elmissouri16 

Not yet. Day jobs keeping me quite busy.

**Comment by ajaydsouza** [comment]
This has now been implemented in 57af43a
